### ISSUE TITLE
Deleting branch fails due to missing new ref

### ISSUE THREAD

**Issue by sigv** [hmcmanus/yaml-validator-hook#14]
Attempting to delete a branch using `git push origin :branchname` results in the following failure:

```plain
remote: Repository hook com.mcmanus.scm.stash.yaml-validator-hook:yaml-validator-hook failed
remote: Commit '0000000000000000000000000000000000000000' does not exist in repository 'foobar'.
```

The stacktrace points at [YamlValidatorPreReceiveRepositoryHook.java:97](https://github.com/hmcmanus/yaml-validator-hook/blob/3.2.2/src/main/java/com/mcmanus/scm/stash/hook/YamlValidatorPreReceiveRepositoryHook.java#L97) as can be seen below:

```plain
com.atlassian.bitbucket.commit.NoSuchCommitException: Commit '0000000000000000000000000000000000000000' does not exist in repository 'foobar'.
    ... frames trimmed
    at com.mcmanus.scm.stash.hook.YamlValidatorPreReceiveRepositoryHook.findCommitsToCheck(YamlValidatorPreReceiveRepositoryHook.java:97)
    at com.mcmanus.scm.stash.hook.YamlValidatorPreReceiveRepositoryHook.onReceive(YamlValidatorPreReceiveRepositoryHook.java:71)
    ... frames trimmed
```

**Comment by sigv** [comment]
We are seeing this behavior on the latest version (3.2.2) of the plugin with the latest version (5.9.1) of Bitbucket, but I doubt it matters for this case.
