### ISSUE TITLE
Issue with Bitbucket v4.14.2

### ISSUE THREAD

**Issue by bbgobie** [hmcmanus/yaml-validator-hook#7]
Thanks for this plugin, we recently upgraded to v4.14.2 of Bitbucket and this plugin is no longer working for us.  Every push is decliend with something like this:
remote: Hook com.mcmanus.scm.stash.hook.YamlValidatorPreReceiveRepositoryHook fa                                                iled. Error:
remote: null

**Comment by hmcmanus** [comment]
Hey there. Thanks for letting me know and raising the issue. I'll get to it as soon as I can. Probably will be next week that I'll get a fix out.

**Comment by Nightfirecat** [comment]
Bump.

We seem to be having this issue in Bitbucket v4.9.1 as well.

**Comment by hmcmanus** [comment]
Hey @Nightfirecat, Just wondering could you send me a example yaml that you are pushing. And the commands. Are you committing on a branch? Merging a branch to master? Just would like something more to test that my simple yaml to make sure everything is working. I've updated to the latest bitbucket version (4.14.3) and can test locally that everything is OK.

**Comment by hmcmanus** [comment]
Also if you are receiving an error then could you please copy and paste the stack trace so that I can have a look?

**Comment by Nightfirecat** [comment]
Unfortunately, I'm only a member on the instance where I'm seeing the issue. I'll see if I can reproduce this at work next week and provide a test case, at least, as well as reach out to our instance admins to get a stack trace if possible.

I can say that I noticed the issue just while attempting pushes, not merges; I didn't try to turn on the hook, then merge a badly-formatted YAML file afterwards.

**Comment by hmcmanus** [comment]
That's cool. If you are just noticing it with normal pushes then that's problem enough. I'll release a new version anyway and see if by simply updating it on your instance has any effect. Though I'm not sure how. Lets see how it goes.

**Comment by KimNorgaard** [comment]
We also see a nullpointerexception that happens when we commit changes to a git submodule with changed yaml files in it. The submodule also has the yaml validation plugin enabled and we get no errors when pushing changes to the submodule itself.

The exception we get is:
```
2017-08-18 10:47:54,299 WARN  [threadpool:thread-3] XX @3QEMNEx647x441334x0 rz71hf 77.243.49.62 SSH - git-receive-pack '/XX/XX-XX.git' c.a.s.i.h.r.PreReceiveRepositoryHookAdapter Receive Hook com.mcmanus.scm.stash.hook.YamlValidatorPreReceiveRepositoryHook failed.
java.lang.NullPointerException: null
        at com.mcmanus.scm.stash.hook.YamlValidatorPreReceiveRepositoryHook.addFileChangesOnCommit(YamlValidatorPreReceiveRepositoryHook.java:173)
        at com.mcmanus.scm.stash.hook.YamlValidatorPreReceiveRepositoryHook.onReceive(YamlValidatorPreReceiveRepositoryHook.java:74)
        at com.atlassian.stash.internal.hook.repository.PreReceiveRepositoryHookAdapter$1.visit(PreReceiveRepositoryHookAdapter.java:38)
        at com.atlassian.stash.internal.hook.repository.PreReceiveRepositoryHookAdapter$1.visit(PreReceiveRepositoryHookAdapter.java:33)
        at com.atlassian.stash.internal.hook.repository.DefaultRepositoryHookService$RepositoryHookPagedTransactionCallback.doInTransaction(DefaultRepositoryHookService.java:573)
        at com.atlassian.stash.internal.hook.repository.DefaultRepositoryHookService$RepositoryHookPagedTransactionCallback.doInTransaction(DefaultRepositoryHookService.java:549)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
        at com.atlassian.stash.internal.hook.repository.DefaultRepositoryHookService.visitEnabledHooks(DefaultRepositoryHookService.java:279)
        at com.atlassian.stash.internal.plugin.OsgiSafeProxyProvider$1.invoke(OsgiSafeProxyProvider.java:93)
        at com.atlassian.stash.internal.hook.repository.PreReceiveRepositoryHookAdapter.onReceive(PreReceiveRepositoryHookAdapter.java:33)
        at com.atlassian.stash.internal.hook.DefaultBuiltInHookHandlerFactory$1.handle(DefaultBuiltInHookHandlerFactory.java:44)
        at com.atlassian.stash.internal.hook.DefaultHookService.doHandleRequest(DefaultHookService.java:303)
        at com.atlassian.stash.internal.hook.DefaultHookService.handleRequest(DefaultHookService.java:289)
        at com.atlassian.stash.internal.hook.DefaultHookService.handleRawRequest(DefaultHookService.java:230)
        at com.atlassian.stash.internal.hook.DefaultHookService$1.lambda$run$0(DefaultHookService.java:197)
        at com.atlassian.stash.internal.concurrent.StateTransferringExecutor$StateTransferringRunnable.run(StateTransferringExecutor.java:70)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.lang.Thread.run(Thread.java:745)
        ... 35 frames trimmed
```

As mentioned, the submodule validates by itself which makes me think that it is not a problem with the YAML.

This works:
```
cd my-submodule
vi my-yaml.yaml
git commit
git push
```
This does not (continued from above):
```
cd ..
git commit
git push
Counting objects: 2, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (2/2), 250 bytes | 250.00 KiB/s, done.
Total 2 (delta 1), reused 0 (delta 0)
remote: Hook com.mcmanus.scm.stash.hook.YamlValidatorPreReceiveRepositoryHook failed. Error: 
remote: null
To ssh://X.Y.Z:7999/XX/XX.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'ssh://git@X.Y.Z:7999/XX/XX.git'
```

**Comment by hmcmanus** [comment]
Fixed in version 3.2.2

**Comment by bbgobie** [comment]
This seems to still be broken for us.
Counting objects: 4, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 548 bytes | 0 bytes/s, done.
Total 4 (delta 3), reused 0 (delta 0)
remote: Hook com.mcmanus.scm.stash.hook.YamlValidatorPreReceiveRepositoryHook failed. Error:
remote: null

**Comment by hmcmanus** [comment]
Damnit. I'll have another look. I don't think I've tested on that particular version of bitbucket so maybe I'll try to get that version up and running and see if I can recreate it. @bbgobie Are you still on 4.14.2?

Also, do you have a submodule in your repository?

**Comment by hmcmanus** [comment]
Also @bbgobie - could you please forward on the stack trace in the same way that @KimNorgaard has done above?

**Comment by hmcmanus** [comment]
I'm going to close this issue as it's quite old now and a older version of bitbucket. Hoping that with new upgrades and testing that it is no longer a problem.
